from backend.app.models.user import User
from backend.app.models.course import Course
from backend.app.models.module import Module
from backend.app.models.training_content import TrainingContent
from backend.app.models.quiz import Quiz
from backend.app.models.question import Question
from backend.app.models.answer import Answer
from backend.app.models.course_assignment import CourseAssignment
from backend.app.models.module_progress import ModuleProgress
from backend.app.models.quiz_attempt import QuizAttempt