"""add course assignment deadline

Revision ID: 598bed8fe87b
Revises: 21fa06509513
Create Date: 2026-09-01 14:31:04.837825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '598bed8fe87b'
down_revision: Union[str, Sequence[str], None] = '21fa06509513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_assignments', sa.Column('deadline', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_assignments', 'deadline')
    # ### end Alembic commands ###
