"""add title and description to training contents

Revision ID: 75becadfce9a
Revises: bbb0ce53166a
Create Date: 2026-08-28 17:59:09.649510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75becadfce9a'
down_revision: Union[str, Sequence[str], None] = 'bbb0ce53166a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_contents', sa.Column('title', sa.String(length=200), nullable=True))
    op.add_column('training_contents', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_contents', 'description')
    op.drop_column('training_contents', 'title')
    # ### end Alembic commands ###
