"""add deadline reminder sent timestamp

Revision ID: 7a4c79e82f01
Revises: 598bed8fe87b
Create Date: 2026-09-01 16:49:23.701689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a4c79e82f01'
down_revision: Union[str, Sequence[str], None] = '598bed8fe87b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_assignments', sa.Column('deadline_reminder_sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_assignments', 'deadline_reminder_sent_at')
    # ### end Alembic commands ###
